image: ubuntu:bionic

cache:
  paths:
  - .m2/
  - .gradle/

before_script:
- apt-get --quiet update --yes
- apt-get install --yes gnupg2 apt-utils software-properties-common
- apt-get install --yes locales >/dev/null
- echo "en_US UTF-8" > /etc/locale.gen
- locale-gen en_US.UTF-8
- export LANG=en_US.UTF-8
- export LANGUAGE=en_US:en
- export LC_ALL=en_US.UTF-8
- apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 0xB1998361219BD9C9
- apt-add-repository 'deb http://repos.azulsystems.com/ubuntu stable main'
- apt-get --quiet update --yes
- apt-get --quiet install --yes zulu-9
- apt-get --quiet install --yes graphviz

- chmod +x ./gradlew

build:
  script:
  - ./gradlew buildCI --scan
  artifacts:
    when: always
    paths:
    - build/site/
